version: '2'

services:
  db:
    image: mongo:latest
    networks:
      mongo_net:
        ipv4_address: 172.16.0.2
  dbseed:
    build: ./mongodb-seed
    networks:
      mongo_net:
        ipv4_address: 172.16.0.3
  app:
    build: ./api
    volumes: 
    - ./api/:/api
    ports:
    - 5001:5001
    networks:
      mongo_net:
        ipv4_address: 172.16.0.4

networks:
  mongo_net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.0.0/24
        gateway: 172.16.0.1 